
class emoji:
    like = '😳'
    dislike = '😶'
    report = '👁️‍'
    back = '🚪'
    search = '🔍'
    settings = '⚙'
    fax = '📠'

    talk = '💬'
    camera = '📸'
    save = '📥'

    smile = '🙂'
    laughs = '😃'
    happiness = '😁'
    kiss = '😘'
    crazy = '🤪'
    cowboy = '🤠'
    shyhands = '👉🏻👈🏻'
    damn = '😈'
    glasses = '😎'
    censorship = '🤬'
    crying = '😭'
    brokenheart = '💔'
    redheart = '❤'
    orangeheart = '🧡'
    purpleheart = '💜'
    party = '🥳'
    nauseous = '🤢'
    sad = '😔'
